### ISSUE TITLE
Jakie drugie API?

### ISSUE THREAD

**Issue by plyta244** [ProjektVue/StudentsApp#25]
W wymaganiach projektu jest żeby użyć 2 API. 1 to może być grawatar, macie pomysł na drugi?

**Comment by kambla** [comment]
Wysyłanie i otrzymywanie wydarzeń na Twitterze. Można rozważyć coś takiego.
[](https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/new-event)

**Comment by plyta244** [comment]
kurcze problem polega na tym, że trzeba tam mieć prywatny klucz. Teraz jako że nie chcemy żeby aplikacja bardzo się rozbudowała, potrzebujemy jakiegoś API, które nie wymaga dużego nakładu pracy... szukajmy dalej

**Comment by kambla** [comment]
Kalendarz dni wolnych. Może być przydatne 
https://date.nager.at/

**Comment by plyta244** [comment]
Hmm. mam pomysł. Możemy skorzystać z gravatara, a druga opcja to pobieranie lokalizacji użytkownika za pomocą api przegladarki i prefilowanie formularza rejestracji (tam trzeba wpisać lokalizację - kraj i miasto) i będziemy mieli 2 API. Co Ty na to @kambla?

**Comment by kambla** [comment]
Dobry pomysł i dobra funkcjonalność. Skorzystajmy z tego
